sudo: required

services:
  - docker

language: python
python:
  - 3.5

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

jobs:
  include:
    - stage: build and push
      script:
      - docker build -t helloworld:test .
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker tag helloworld:test $DOCKER_USERNAME/helloworld:test
      - docker push $DOCKER_USERNAME/helloworld:test

    - stage: test docker image
      test:
      - docker run --rm $DOCKER_USERNAME/helloworld:test

  after_success:
  - test $TRAVIS_BRANCH = "master" &&
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker tag helloworld:stage $DOCKER_USERNAME/helloworld:latest
    - docker push $DOCKER_USERNAME/helloworld:latest
  - test $TRAVIS_BRANCH = "stage" &&
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker tag helloworld:stage $DOCKER_USERNAME/helloworld:stage
    - docker push $DOCKER_USERNAME/helloworld:stage
