sudo: required

services:
  - docker

language: python
python:
  - 3.5

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  
jobs:
  include:
    - stage: build stage test
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t helloworld:stage .
      - docker tag helloworld:stage $DOCKER_USERNAME/helloworld:stage
      - docker push $DOCKER_USERNAME/helloworld:stage
    - stage: test docker image
      script:
      - docker run --rm $DOCKER_USERNAME/helloworld:stage
    - stage: upload image as :latest
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker pull $DOCKER_USERNAME/helloworld:stage
      - docker tag $DOCKER_USERNAME/helloworld:stage $DOCKER_USERNAME/helloworld:latest
      - docker push $DOCKER_USERNAME/helloworld:latest
