sudo: required

services:
  - docker

language: python
python:
  - 3.5

jobs:
  include:
    - stage: Build Docker Image
    script:
      - docker build -t helloworld:stage .
    - stage: Test Docker Image
    script: docker run --tm helloworld:stage
    
