sudo: required

services:
  - docker

language: python
python:
  - 3.5

before_install:
  - sudo apt-get update >/dev/null 2>&1
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce >/dev/null 2>&1

jobs:
  include:
    - stage: build and push
      script:
      - docker build -t helloworld:test .
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker tag helloworld:test $DOCKER_USERNAME/helloworld:test
      - docker push $DOCKER_USERNAME/helloworld:test

    - stage: test docker image
      script:
      - docker run --rm $DOCKER_USERNAME/helloworld:test
    - stage: upload stage/master to dockerhub
      script:
        - test $TRAVIS_BRANCH = "master" &&
          - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          - docker tag helloworld:stage $DOCKER_USERNAME/helloworld:latest
          - docker push $DOCKER_USERNAME/helloworld:latest
        - test $TRAVIS_BRANCH = "stage" &&
          - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          - docker tag helloworld:stage $DOCKER_USERNAME/helloworld:stage
          - docker push $DOCKER_USERNAME/helloworld:stage
