sudo: required

services:
  - docker

language: python
python:
  - 3.5

jobs:
  include:
    - stage: build stage test
      script:
      - docker build -t helloworld:stage .
    - stage: test docker image
      script:
      - docker run --rm helloworld:stage
