sudo: required

services:
  - docker

language: python

install:
  - sudo apt-get update >/dev/null 2>&1
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce >/dev/null 2>&1

script:
  - docker build -t helloworld:test .
  - docker run --rm helloworld:test

after_success:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      if [ "$TRAVIS_BRANCH" = "master" ]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        docker tag helloworld:test $DOCKER_USERNAME/helloworld:latest
        docker push $DOCKER_USERNAME/helloworld:latest
      else
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        docker tag helloworld:test $DOCKER_USERNAME/helloworld:stage
        docker push $DOCKER_USERNAME/helloworld:latest
      fi
    fi
